"use strict";

window.FEELBG_EVENTS = {
    upcomingEvents: [
        {
            id: 1,
            title: "Sava Center Summer Concert Series",
            title_sr: "Letnja serija koncerata u Sava Centru",
            type: "concert",
            venue: "Sava Center, Novi Beograd",
            address: "Kumodraž 1, Belgrade",
            description: "The iconic Sava Center hosts a spectacular summer concert series featuring top Serbian and Balkan acts under the stars.",
            description_sr: "Ikonični Sava Centar domaćin je spektakularnih letnjих koncerata sa vrhunskim srpskim i balkanskim umetnicima pod zvezdama.",
            image: "slike/sava_concert.jpg",
            date: "June 15, 2026",
            date_sr: "15. Jun 2026",
            time: "20:00 - 23:30",
            price: "1200–3500 RSD",
            status: "live",
            rating: 4.8,
            lat: 44.8048,
            lng: 20.4198,
            tags: ["concert", "music", "live", "summer"],
        },
        {
            id: 2,
            title: "EXIT Festival Preview Night",
            title_sr: "Noć otvaranja EXIT Festivala",
            type: "festival",
            venue: "Petrovaradin Fortress, Novi Sad",
            address: "Petrovaradin, Novi Sad",
            description: "The legendary EXIT Festival kicks off with a preview night — buses from Belgrade's Trg Nikole Pašića depart daily.",
            description_sr: "Legendarni EXIT Festival počinje sa predvečerom - autobusi kreću svakodnevno sa Trga Nikole Pašića.",
            image: "slike/exit_festival.jpg",
            date: "June 22-25, 2026",
            date_sr: "22-25. Jun 2026",
            time: "18:00 - 06:00",
            price: "4500 RSD Day Pass",
            status: "upcoming",
            rating: 4.9,
            lat: 44.6719,
            lng: 19.8754,
            tags: ["festival", "music", "nightlife", "balkan"],
        },
        {
            id: 3,
            title: "Skadarlija Jazz Night",
            title_sr: "Džez veče u Skadarliji",
            type: "music",
            venue: "Skadarlija Bohemian Quarter",
            address: "Skadarska ulica, Skadarlija, Belgrade",
            description: "Every Friday, Skadarlija's cobblestone streets come alive with open-air jazz, traditional gusle players, and folk dancers.",
            description_sr: "Svakog petka, ulice Skadarlije žive od džeza, tradicionalnih guslara i narodnih plesača.",
            image: "slike/skadarlija_jazz.jpg",
            date: "Every Friday",
            date_sr: "Svakog petka",
            time: "21:00 - 00:00",
            price: "Free Entry",
            status: "live",
            rating: 4.7,
            lat: 44.8183,
            lng: 20.4638,
            tags: ["jazz", "live music", "cultural", "free"],
        },
        {
            id: 4,
            title: "Belgrade Design Week",
            title_sr: "Nedelja Beogradskog Dizajna",
            type: "culture",
            venue: "Savamala Creative District",
            address: "Savamala, Belgrade",
            description: "Savamala's galleries and warehouses open for a week-long celebration of Serbian design, art installations and urban culture.",
            description_sr: "Galerije i skladišta Savamale otvorena za nedeljnu proslavu srpskog dizajna, umetnučkih instalacija i urbane kulture.",
            image: "slike/design_week.jpg",
            date: "June 16-22, 2026",
            date_sr: "16-22. Jun 2026",
            time: "11:00 - 22:00",
            price: "500–800 RSD",
            status: "upcoming",
            rating: 4.6,
            lat: 44.8188,
            lng: 20.4456,
            tags: ["design", "art", "culture", "contemporary"],
        },
        {
            id: 5,
            title: "Belgrade Street Food Festival",
            title_sr: "Festival Beogradske Ulične Hrane",
            type: "food",
            venue: "Ušće Park, Novi Beograd",
            address: "Ušće Park, Novi Beograd, Belgrade",
            description: "Over 80 vendors from across Serbia and the Balkans gather for a 3-day open-air feast of grilled meats, pastries, and local wines.",
            description_sr: "Preko 80 prodavaca iz Srbije i Balkana na 3-dnevnoj proslavi pečenog mesa, pečenja, slastica i lokalnog vina.",
            image: "slike/food_fest.jpg",
            date: "June 28-30, 2026",
            date_sr: "28-30. Jun 2026",
            time: "12:00 - 23:00",
            price: "Free Entry (pay per item)",
            status: "upcoming",
            rating: 4.8,
            lat: 44.8184,
            lng: 20.4046,
            tags: ["food", "festival", "serbian", "summer"],
        },
        {
            id: 6,
            title: "Danube Docks Art & Music Festival",
            title_sr: "Festival Umetnosti i Muzike - Dunavski Pristani",
            type: "festival",
            venue: "Danube Waterfront, Novi Beograd",
            address: "Ada Ciganlija Waterfront, Belgrade",
            description: "A weekend celebration of emerging Serbian artists, electronic music, and indie performances along the Danube riverside.",
            description_sr: "Vikend proslava nastajućih srpskih umetnika, elektronske muzike i indie performansi duž Dunavske obale.",
            image: "slike/danube_festival.jpg",
            date: "July 5-6, 2026",
            date_sr: "5-6. Jul 2026",
            time: "16:00 - 02:00",
            price: "800 RSD single day / 1200 RSD weekend",
            status: "upcoming",
            rating: 4.5,
            lat: 44.7955,
            lng: 20.421,
            tags: ["music", "art", "electronic", "danube"],
        },
        {
            id: 7,
            title: "Splav Zone - Eternal Float Party",
            title_sr: "Splav Zona - Večita Plovka Zabava",
            type: "nightlife",
            venue: "Sava River Floating Clubs",
            address: "Savski Kej, Novi Beograd",
            description: "Belgrade's legendary floating nightclub district comes alive every night with international DJs, live bands, and 360° Danube views.",
            description_sr: "Legendarni lebdeći noćni klub Beograda živi svake noći sa međunarodnim DJ-ima, živim bendovima i 360° pogledom na Dunav.",
            image: "slike/splav_party.jpg",
            date: "Daily",
            date_sr: "Svaki dan",
            time: "23:00 - 06:00",
            price: "5–15 EUR entry",
            status: "live",
            rating: 4.9,
            lat: 44.815,
            lng: 20.42,
            tags: ["nightlife", "clubs", "dj", "sava"],
        },
        {
            id: 8,
            title: "Nikola Tesla Night Lecture Series",
            title_sr: "Predavanja O Nikoli Tesli",
            type: "culture",
            venue: "Nikola Tesla Museum",
            address: "Krunska 51, Vračar, Belgrade",
            description: "Evening lectures on Tesla's life, inventions, and legacy with expert historians and interactive museum tours.",
            description_sr: "Večernja predavanja o Teslinoj biografiji, izumima i nasleđu sa stručnjacima i interaktivnim muzejskim turima.",
            image: "slike/tesla_museum.jpg",
            date: "Thursdays",
            date_sr: "Četvrtci",
            time: "19:00 - 20:30",
            price: "300 RSD",
            status: "live",
            rating: 4.7,
            lat: 44.8085,
            lng: 20.466,
            tags: ["culture", "history", "science", "museum"],
        },
        {
            id: 9,
            title: "Bohemian Brunch & Jazz Sundays",
            title_sr: "Bohemska Doručak i Džez Nedelje",
            type: "music",
            venue: "Multiple Skadarlija Venues",
            address: "Skadarska ulica & surrounding area, Belgrade",
            description: "Sunday morning tradition featuring live jazz duos, local pastries, Serbian coffee, and authentic folk atmosphere.",
            description_sr: "Nedeljna tradidcija sa žitim džez duetima, lokalnim pekarskim proizvodima, srpskom kafom i autentičnom narodnom atmosferom.",
            image: "slike/brunch_jazz.jpg",
            date: "Every Sunday",
            date_sr: "Svake nedelje",
            time: "10:00 - 13:00",
            price: "Free (food/drinks available)",
            status: "live",
            rating: 4.6,
            lat: 44.8183,
            lng: 20.4638,
            tags: ["brunch", "jazz", "cultural", "weekend"],
        },
        {
            id: 10,
            title: "Summer Cinema at Kalemegdan",
            title_sr: "Letnina Bioskop na Kalemegdanu",
            type: "culture",
            venue: "Kalemegdan Fortress",
            address: "Kalemegdan Park, Stari Grad, Belgrade",
            description: "Outdoor cinema beneath the fortress with classic Serbian films, art house cinema, and international indie productions.",
            description_sr: "Otvoreni bioskop ispod tvrđave sa klasičnim srpskim filmovima, umetničkim bioskopom i međunarodnim indie produkcijama.",
            image: "slike/kalemegdan.jpg",
            date: "June-August (nightly)",
            date_sr: "Jun-August (svake noći)",
            time: "21:00 - 23:30",
            price: "300 RSD",
            status: "upcoming",
            rating: 4.8,
            lat: 44.8227,
            lng: 20.4513,
            tags: ["cinema", "culture", "summer", "outdoor"],
        },
    ],
};
