"use strict";

window.FEELBG_VENUES = {
    restaurants: [
        {
            name: "Temperament",
            cuisine: "serbian",
            cuisineLabel: "Modern Serbian",
            price: "moderate",
            priceLabel: "€15–25 per person",
            area: "Stari Grad",
            address: "Karađorđeva 2-4, Beton Hala",
            rating: 4.7,
            badge: "popular",
            description:
                "Contemporary Serbian restaurant with creative dishes and modern ambiance",
            lat: 44.8135,
            lng: 20.4528,
            image: "slike/temperament.jpg",
        },
        {
            name: "Butik 3",
            cuisine: "international",
            cuisineLabel: "International · Boutique",
            price: "upscale",
            priceLabel: "€25–40 per person",
            area: "Stari Grad",
            address: "Obilićev Venac, Stari Grad",
            rating: 4.6,
            description:
                "Exclusive boutique restaurant in the heart of Belgrade's center",
            lat: 44.8190,
            lng: 20.4600,
            image: "assets/images/restorani/dekstop.jpg",
        },
        {
            name: "Zlatni Bokal",
            cuisine: "serbian",
            cuisineLabel: "Traditional Serbian",
            price: "moderate",
            priceLabel: "€12–22 per person",
            area: "Stari Grad",
            address: "Skadarska 26, Skadarlija",
            rating: 4.8,
            badge: "topRated",
            description:
                "Golden Goblet - authentic Skadarlija kafana with traditional Serbian cuisine",
            lat: 44.8185,
            lng: 20.4632,
            image: "slike/Zlatni Bokal.jpg",
        },
        {
            name: "Bottega",
            cuisine: "mediterranean",
            cuisineLabel: "Mediterranean · Gallery",
            price: "upscale",
            priceLabel: "€22–38 per person",
            area: "Savski Venac",
            address: "Bulevar Vudro Vilsona 12, Belgrade Waterfront",
            rating: 4.7,
            badge: "trending",
            description:
                "Gallery restaurant with Mediterranean cuisine at Belgrade Waterfront",
            lat: 44.8148,
            lng: 20.4480,
            image: "slike/bottega.webp",
        },
        {
            name: "Le Petit Bistro NBG",
            cuisine: "french",
            cuisineLabel: "French · Bistro",
            price: "upscale",
            priceLabel: "€20–35 per person",
            area: "Novi Beograd",
            address: "Džona Kenedija, Novi Beograd",
            rating: 4.6,
            description:
                "Charming French bistro with classic cuisine in New Belgrade",
            lat: 44.8058,
            lng: 20.4198,
            image: "slike/lepetit_bistro.jpg",
        },
        {
            name: "Suvinjon",
            cuisine: "contemporary",
            cuisineLabel: "Contemporary · Wine",
            price: "moderate",
            priceLabel: "€18–28 per person",
            area: "Novi Beograd",
            address: "Milutina Milankovića, Novi Beograd",
            rating: 4.5,
            description:
                "Wine-focused restaurant with contemporary Serbian dishes",
            lat: 44.8065,
            lng: 20.423,
            image: "assets/images/restorani/bay.jpg",
        },
        {
            name: "Dva Jelena",
            cuisine: "serbian",
            cuisineLabel: "Traditional Serbian",
            price: "moderate",
            priceLabel: "€10–20 per person",
            area: "Stari Grad",
            address: "Skadarska 32, Skadarlija",
            rating: 4.7,
            badge: "popular",
            description:
                "Two Deer — legendary Skadarlija kafana with tamburitza music",
            lat: 44.818,
            lng: 20.464,
            image: "slike/logo/dva jelena.jpg",
        },
        {
            name: "Sport",
            cuisine: "grill",
            cuisineLabel: "Serbian · Grill",
            price: "moderate",
            priceLabel: "€14–24 per person",
            area: "Voždovac",
            address: "Vojvode Stepe, Autokomanda, Voždovac",
            rating: 4.4,
            description:
                "Popular sport-themed restaurant with excellent Serbian grill specialties",
            lat: 44.7950,
            lng: 20.4650,
            image: "slike/sport.jpg",
        },
        {
            name: "Sakura",
            cuisine: "japanese",
            cuisineLabel: "Japanese · Sushi",
            price: "upscale",
            priceLabel: "€25–45 per person",
            area: "Stari Grad",
            address: "Karađorđeva 2-4, Beton Hala",
            rating: 4.7,
            badge: "trending",
            description:
                "Premium Japanese sushi and sashimi with sake pairing menu",
            lat: 44.8135,
            lng: 20.4528,
            image: "slike/sakura.jpg",
        },
        {
            name: "Leto",
            cuisine: "contemporary",
            cuisineLabel: "Modern Serbian",
            price: "moderate",
            priceLabel: "€16–26 per person",
            area: "Novi Beograd",
            address: "Jurija Gagarina, Novi Beograd",
            rating: 4.5,
            description:
                "Summer-inspired restaurant with fresh, modern Serbian cuisine",
            lat: 44.8070,
            lng: 20.4200,
            image: "slike/logo/salon.jpg",
        },
    ],

    nightlife: [
        {
            name: "Money",
            cuisine: "electronic",
            cuisineLabel: "Club · Electronic",
            price: "upscale",
            priceLabel: "€12–20 entry",
            area: "Savski Venac",
            address: "Savski Venac, Belgrade Waterfront",
            rating: 4.8,
            badge: "topRated",
            description:
                "Premier nightclub at Belgrade Waterfront with top electronic DJs",
            lat: 44.8148,
            lng: 20.4480,
            image: "assets/images/belgrade-by-night-4576220_1280.jpg",
        },
        {
            name: "Lasta",
            cuisine: "mainstream",
            cuisineLabel: "Splav · Party",
            price: "moderate",
            priceLabel: "€5–15 entry",
            area: "Novi Beograd",
            address: "Savski Kej, Novi Beograd",
            rating: 4.7,
            badge: "popular",
            description:
                "Legendary floating nightclub on the Sava with top DJs and open-air dancing",
            lat: 44.8150,
            lng: 20.4200,
            image: "slike/lasta.jpg",
        },
    ],

    attractions: [
        {
            name: "Kalemegdan Fortress",
            cuisine: "historic",
            cuisineLabel: "Historic Fortress",
            area: "Stari Grad",
            address: "Kalemegdan Park, Stari Grad",
            rating: 4.9,
            badge: "topRated",
            description:
                "Ancient fortress at the confluence of the Sava and Danube rivers",
            lat: 44.8227,
            lng: 20.4513,
            image: "assets/atractions/kalis.jfif",
        },
        {
            name: "Skadarlija Bohemian Quarter",
            cuisine: "cultural",
            cuisineLabel: "Bohemian Street",
            area: "Stari Grad",
            address: "Skadarska ulica, Skadarlija",
            rating: 4.8,
            badge: "popular",
            description:
                "Cobblestone street lined with kafanas, art galleries and street musicians",
            lat: 44.8183,
            lng: 20.4638,
            image: "assets/atractions/skadarl.jpg",
        },
        {
            name: "Ada Ciganlija",
            cuisine: "nature",
            cuisineLabel: "Beach · Recreation",
            area: "Čukarica",
            address: "Ada Ciganlija, Čukarica",
            rating: 4.9,
            badge: "topRated",
            description:
                "Belgrade's Sea — river island paradise with beaches, sports and cafés",
            lat: 44.7833,
            lng: 20.4,
            image: "assets/images/ada-ciganlija.jpg",
        },
        {
            name: "Saint Sava Temple",
            cuisine: "religious",
            cuisineLabel: "Orthodox Church",
            area: "Vračar",
            address: "Krušedolska 2a, Vračar",
            rating: 4.9,
            badge: "topRated",
            description:
                "One of the largest Orthodox churches in the world with stunning gold mosaics",
            lat: 44.7981,
            lng: 20.4691,
            image: "assets/atractions/sveti.jpg",
        },
        {
            name: "Nikola Tesla Museum",
            cuisine: "museum",
            cuisineLabel: "Science Museum",
            area: "Vračar",
            address: "Krunska 51, Vračar",
            rating: 4.8,
            badge: "popular",
            description:
                "The world's only museum dedicated to inventor Nikola Tesla with interactive exhibits",
            lat: 44.8052,
            lng: 20.4707,
            image: "assets/atractions/nidza.jpg",
        },
        {
            name: "Topčider Park",
            cuisine: "nature",
            cuisineLabel: "Royal Park",
            area: "Topčider",
            address: "Topčiderski park, Topčider",
            rating: 4.7,
            description:
                "Royal park with 200-year-old plane trees and elegant pavilions",
            lat: 44.7837,
            lng: 20.446,
            image: "assets/images/topcider-park.jpg",
        },
        {
            name: "Gardoš Tower",
            cuisine: "historic",
            cuisineLabel: "Historic Tower",
            area: "Zemun",
            address: "Gardoš, Zemun",
            rating: 4.7,
            badge: "popular",
            description:
                "Millennium Tower with panoramic views of the Danube and old Zemun",
            lat: 44.8483,
            lng: 20.4097,
            image: "assets/atractions/gardos.jpg",
        },
        {
            name: "National Museum",
            cuisine: "museum",
            cuisineLabel: "Art & History Museum",
            area: "Stari Grad",
            address: "Trg Republike 1a, Stari Grad",
            rating: 4.6,
            description:
                "Serbia's largest museum with 400,000+ artifacts spanning 3,000 years",
            lat: 44.8167,
            lng: 20.4594,
            image: "assets/atractions/muzej nac.jpg",
        },
        {
            name: "Zemun Quay",
            cuisine: "nature",
            cuisineLabel: "Riverside Walk",
            area: "Zemun",
            address: "Kej oslobođenja, Zemun",
            rating: 4.7,
            badge: "trending",
            description:
                "Charming riverside promenade with cafés, swans and Danube sunsets",
            lat: 44.8397,
            lng: 20.4011,
            image: "assets/atractions/zemun.jpeg",
        },
        {
            name: "Belgrade Fortress Military Museum",
            cuisine: "museum",
            cuisineLabel: "Military Museum",
            area: "Stari Grad",
            address: "Kalemegdan bb, Stari Grad",
            rating: 4.5,
            description:
                "Outdoor tanks and artillery plus indoor exhibits tracing Serbia's military history",
            lat: 44.823,
            lng: 20.4518,
            image: "assets/atractions/miltary.jfif",
        },
    ],
};
