"use strict";

window.FEELBG_VENUES = {
    restaurants: [
        {
            name: "Ambar",
            cuisine: "serbian",
            cuisineLabel: "Serbian Cuisine",
            price: "upscale",
            priceLabel: "€25–40 per person",
            area: "Stari Grad",
            address: "Karađorđeva 2-4, Stari Grad",
            rating: 4.9,
            badge: "topRated",
            description:
                "Award-winning Balkan cuisine with unlimited small plates and Sava river views",
            lat: 44.8135,
            lng: 20.4528,
            image: "slike/logo/ambar.jpg",
        },
        {
            name: "Tri Šešira",
            cuisine: "serbian",
            cuisineLabel: "Traditional Serbian",
            price: "moderate",
            priceLabel: "€12–22 per person",
            area: "Skadarlija",
            address: "Skadarska 29, Skadarlija",
            rating: 4.7,
            badge: "popular",
            description:
                "Iconic Skadarlija kafana serving traditional Serbian dishes since 1864",
            lat: 44.8185,
            lng: 20.4632,
            image: "slike/logo/tri sesira.jpg",
        },
        {
            name: "Salon 1905",
            cuisine: "serbian",
            cuisineLabel: "Serbian Fine Dining",
            price: "upscale",
            priceLabel: "€30–50 per person",
            area: "Stari Grad",
            address: "Kralja Petra 6, Stari Grad",
            rating: 4.9,
            badge: "topRated",
            description:
                "Elegant Serbian cuisine with live orchestra in a Belle Époque salon",
            lat: 44.8196,
            lng: 20.4601,
            image: "slike/logo/salon.jpg",
        },
        {
            name: "Lorenzo & Kakalamba",
            cuisine: "fineDining",
            cuisineLabel: "Fine Dining · Fusion",
            price: "fine-dining",
            priceLabel: "€45–80 per person",
            area: "Stari Grad",
            address: "Cvijićeva 110, Stari Grad",
            rating: 4.9,
            badge: "topRated",
            description:
                "Theatrical fine dining with a multi-course tasting menu experience",
            lat: 44.821,
            lng: 20.4561,
            image: "assets/images/restorani/dekstop.jpg",
        },
        {
            name: "Znak Pitanja",
            cuisine: "serbian",
            cuisineLabel: "Traditional Serbian",
            price: "moderate",
            priceLabel: "€10–18 per person",
            area: "Stari Grad",
            address: "Kralja Petra 6, Stari Grad",
            rating: 4.8,
            badge: "popular",
            description:
                "Belgrade's oldest restaurant (1823) — The Question Mark kafana",
            lat: 44.8202,
            lng: 20.4589,
            image: "slike/logo/znak pitanja.jpg",
        },
        {
            name: "Little Bay",
            cuisine: "international",
            cuisineLabel: "International · Bistro",
            price: "upscale",
            priceLabel: "€20–35 per person",
            area: "Stari Grad",
            address: "Dositejeva 9a, Stari Grad",
            rating: 4.8,
            description:
                "Opera-themed bistro with nightly classical performances",
            lat: 44.8199,
            lng: 20.4594,
            image: "assets/images/restorani/bay.jpg",
        },
        {
            name: "Manufaktura",
            cuisine: "contemporary",
            cuisineLabel: "Modern Serbian",
            price: "moderate",
            priceLabel: "€12–20 per person",
            area: "Dorćol",
            address: "Kralja Petra 13, Dorćol",
            rating: 4.5,
            description:
                "Modern Serbian craft gastronomy in a hip industrial setting",
            lat: 44.8226,
            lng: 20.4638,
            image: "slike/logo/manufaktura.jpg",
        },
        {
            name: "Mala Fabrika Ukusa",
            cuisine: "serbian",
            cuisineLabel: "Serbian · Artisan",
            price: "moderate",
            priceLabel: "€10–18 per person",
            area: "Vračar",
            address: "Svetozara Markovića 48, Vračar",
            rating: 4.8,
            badge: "popular",
            description:
                "Small Factory of Taste — artisan Serbian plates with creative twists",
            lat: 44.8073,
            lng: 20.4701,
            image: "slike/logo/mala fabrika ukusa.webp",
        },
        {
            name: "Comunale Caffè e Cucina",
            cuisine: "italian",
            cuisineLabel: "Italian Cuisine",
            price: "moderate",
            priceLabel: "€12–22 per person",
            area: "Stari Grad",
            address: "Knez Mihailova 12, Stari Grad",
            rating: 4.6,
            description:
                "Authentic Italian in the heart of Belgrade's main pedestrian street",
            lat: 44.8184,
            lng: 20.4577,
            image: "slike/logo/comunale.jpg",
        },
        {
            name: "Bella Napoli",
            cuisine: "italian",
            cuisineLabel: "Italian · Pizza",
            price: "moderate",
            priceLabel: "€8–15 per person",
            area: "Stari Grad",
            address: "Strahinjića Bana 49, Stari Grad",
            rating: 4.5,
            description:
                "Wood-fired Neapolitan pizza and fresh pasta in a lively trattoria",
            lat: 44.8208,
            lng: 20.4572,
            image: "slike/logo/bella napoli.webp",
        },
        {
            name: "Sakura",
            cuisine: "japanese",
            cuisineLabel: "Japanese · Sushi",
            price: "upscale",
            priceLabel: "€25–45 per person",
            area: "Stari Grad",
            address: "Strahinjića Bana 63, Stari Grad",
            rating: 4.7,
            badge: "trending",
            description:
                "Premium Japanese sushi and sashimi with sake pairing menu",
            lat: 44.8214,
            lng: 20.4555,
            image: "slike/logo/sakura.jpg",
        },
        {
            name: "Dva Jelena",
            cuisine: "serbian",
            cuisineLabel: "Traditional Serbian",
            price: "moderate",
            priceLabel: "€10–20 per person",
            area: "Skadarlija",
            address: "Skadarska 32, Skadarlija",
            rating: 4.7,
            badge: "popular",
            description:
                "Two Deer — legendary Skadarlija kafana with tamburitza music",
            lat: 44.818,
            lng: 20.464,
            image: "slike/logo/dva jelena.jpg",
        },
        {
            name: "Franš",
            cuisine: "mediterranean",
            cuisineLabel: "French · Mediterranean",
            price: "upscale",
            priceLabel: "€22–40 per person",
            area: "Dorćol",
            address: "Đure Jakšića 3, Dorćol",
            rating: 4.7,
            description:
                "Refined French-Mediterranean cuisine in a charming courtyard",
            lat: 44.8231,
            lng: 20.4647,
            image: "slike/logo/frans.jpg",
        },
        {
            name: "Langouste",
            cuisine: "seafood",
            cuisineLabel: "Seafood · Mediterranean",
            price: "upscale",
            priceLabel: "€20–40 per person",
            area: "Dorćol",
            address: "Strahinjića Bana 76, Dorćol",
            rating: 4.6,
            description: "Fresh Adriatic seafood and Mediterranean specialties",
            lat: 44.822,
            lng: 20.4648,
            image: "slike/logo/langouste.jpg",
        },
        {
            name: "Bela Reka",
            cuisine: "serbian",
            cuisineLabel: "Serbian  � Grill",
            price: "budget",
            priceLabel: "€5–10 per person",
            area: "Stari Grad",
            address: "Skadarska 15, Stari Grad",
            rating: 4.4,
            description:
                "Hearty Serbian grill and traditional comfort food at local prices",
            lat: 44.8197,
            lng: 20.4592,
            image: "slike/bela reka.jpg",
        },
    ],

    cafes: [
        {
            name: "Hotel Moskva Café",
            cuisine: "coffee",
            cuisineLabel: "Grand Café · Patisserie",
            price: "moderate",
            priceLabel: "€5–12 per person",
            area: "Stari Grad",
            address: "Balkanska 1, Stari Grad",
            rating: 4.9,
            badge: "topRated",
            description:
                "Belgrade's most iconic café since 1908 — legendary Moskva cake and Art Nouveau interiors",
            lat: 44.8143,
            lng: 20.4602,
            image: "slike/logo/hotel moskva.jpg",
        },
        {
            name: "Supermarket Bar",
            cuisine: "cocktail",
            cuisineLabel: "Cocktail · Rooftop",
            price: "moderate",
            priceLabel: "€6–14 per person",
            area: "Savamala",
            address: "Karađorđeva 44, Savamala",
            rating: 4.7,
            badge: "popular",
            description:
                "Trendy rooftop cocktail bar in the heart of Savamala district",
            lat: 44.8141,
            lng: 20.4521,
            image: "slike/logo/supermarket.jpg",
        },
        {
            name: "Smokvica",
            cuisine: "wine",
            cuisineLabel: "Wine · Mediterranean",
            price: "moderate",
            priceLabel: "€8–18 per person",
            area: "Dorćol",
            address: "Kralja Petra 73, Dorćol",
            rating: 4.8,
            badge: "topRated",
            description: "Chic Mediterranean wine bar with a lush garden patio",
            lat: 44.8226,
            lng: 20.4638,
            image: "slike/logo/smokvica.jpg",
        },
        {
            name: "Stara Konoba",
            cuisine: "coffee",
            cuisineLabel: "Traditional Coffee",
            price: "budget",
            priceLabel: "€10-30 per person",
            area: "Stari Grad",
            address: "Cara Uroša 16, Stari Grad",
            rating: 4.6,
            description:
                "Old Belgrade coffee house with live acoustic music and Turkish coffee",
            lat: 44.8208,
            lng: 20.4572,
            image: "slike/logo/stara konoba.jpg",
        },
        {
            name: "Via del Gusto",
            cuisine: "wine",
            cuisineLabel: "Wine Bar",
            price: "moderate",
            priceLabel: "€8–20 per person",
            area: "Vračar",
            address: "Bulevar Kralja Aleksandra 52, Vračar",
            rating: 4.7,
            description:
                "Premium Serbian wine selection with antipasti platters",
            lat: 44.8067,
            lng: 20.469,
            image: "slike/logo/viadelgusto-ezgif.com-webp-to-jpg-converter.jpg"
        },
        {
            name: "Mint Rooftop Bar",
            cuisine: "cocktail",
            cuisineLabel: "Cocktail · Lounge",
            price: "upscale",
            priceLabel: "€12–25 per person",
            area: "Novi Beograd",
            address: "Bulevar Mihajla Pupina 10, Novi Beograd",
            rating: 4.9,
            badge: "topRated",
            description:
                "Sky-high cocktails with panoramic views of Belgrade from the 18th floor",
            lat: 44.8058,
            lng: 20.4198,
            image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&q=80",
        },
        {
            name: "Rekord Bar",
            cuisine: "craft",
            cuisineLabel: "Vinyl · Craft Beer",
            price: "budget",
            priceLabel: "€3–7 per person",
            area: "Dorćol",
            address: "Gospodar Jevremova 28, Dorćol",
            rating: 4.6,
            badge: "trending",
            description:
                "Vinyl record bar with rotating craft beer selection and retro vibes",
            lat: 44.8231,
            lng: 20.4647,
            image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&q=80",
        },
        {
            name: "Balkan Brew",
            cuisine: "craft",
            cuisineLabel: "Craft Brewery",
            price: "moderate",
            priceLabel: "€5–12 per person",
            area: "Savamala",
            address: "Karađorđeva 61, Savamala",
            rating: 4.7,
            badge: "popular",
            description:
                "Craft brewery with 20+ local beers on tap and brewery tours",
            lat: 44.813,
            lng: 20.4533,
            image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80",
        },
        {
            name: "Toro Latin GastroBar",
            cuisine: "cocktail",
            cuisineLabel: "Latin · Cocktail",
            price: "moderate",
            priceLabel: "€7–15 per person",
            area: "Stari Grad",
            address: "Strahinjića Bana 55, Stari Grad",
            rating: 4.6,
            description:
                "Latin-inspired cocktails with tapas in a vibrant setting",
            lat: 44.8204,
            lng: 20.4583,
            image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80",
        },
        {
            name: "Kafeterija",
            cuisine: "coffee",
            cuisineLabel: "Specialty Coffee",
            price: "budget",
            priceLabel: "€2–5 per person",
            area: "Vračar",
            address: "Internacionalnih brigada 55, Vračar",
            rating: 4.5,
            description:
                "Third-wave specialty coffee roasters with pour-over bar",
            lat: 44.8081,
            lng: 20.4685,
            image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
        },
    ],

    nightlife: [
        {
            name: "Klub 20/44",
            cuisine: "electronic",
            cuisineLabel: "Electronic · Techno",
            price: "upscale",
            priceLabel: "€10–20 entry",
            area: "Savamala",
            address: "Savski kej bb, Savamala",
            rating: 4.8,
            badge: "topRated",
            description:
                "Premier club for electronic music on the Sava river bank",
            lat: 44.8138,
            lng: 20.4516,
            image: "slike/44.jpg",
        },
        {
            name: "Freestyler Boat Club",
            cuisine: "mainstream",
            cuisineLabel: "Pop · Dance",
            price: "upscale",
            priceLabel: "€10–25 entry",
            area: "Sava",
            address: "Brod Freestyler, Sava River",
            rating: 4.7,
            badge: "popular",
            description:
                "Legendary floating nightclub on the Sava river with top DJs",
            lat: 44.8148,
            lng: 20.449,
            image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80",
        },
        {
            name: "Drugstore Club",
            cuisine: "electronic",
            cuisineLabel: "Techno · Underground",
            price: "upscale",
            priceLabel: "€8–15 entry",
            area: "Savamala",
            address: "Bulevar vojvode Mišića 12, Savamala",
            rating: 4.7,
            badge: "trending",
            description: "Open-air electronic music venue near Beton Hala",
            lat: 44.8145,
            lng: 20.4502,
            image: "https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=600&q=80",
        },
        {
            name: "Ksenija Jazz Club",
            cuisine: "jazz",
            cuisineLabel: "Jazz · Live Music",
            price: "moderate",
            priceLabel: "€5–12 entry",
            area: "Stari Grad",
            address: "Kralja Petra 56, Stari Grad",
            rating: 4.9,
            badge: "topRated",
            description:
                "Intimate jazz venue with world-class live performances",
            lat: 44.8204,
            lng: 20.4583,
            image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&q=80",
        },
        {
            name: "Ben Akiba Stand-Up",
            cuisine: "comedy",
            cuisineLabel: "Comedy · Entertainment",
            price: "moderate",
            priceLabel: "€5–10 entry",
            area: "Stari Grad",
            address: "Nušićeva 8, Stari Grad",
            rating: 4.6,
            description:
                "Belgrade's premier comedy club with local and international acts",
            lat: 44.8197,
            lng: 20.4592,
            image: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=600&q=80",
        },
        {
            name: "Brankow",
            cuisine: "alternative",
            cuisineLabel: "Alternative · Art",
            price: "moderate",
            priceLabel: "€5–10 entry",
            area: "Savamala",
            address: "Karađorđeva 43, Savamala",
            rating: 4.6,
            badge: "popular",
            description:
                "Art-meets-nightlife venue with rooftop overlooking the Sava",
            lat: 44.8135,
            lng: 20.4528,
            image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80",
        },
        {
            name: "Lasta Club",
            cuisine: "mainstream",
            cuisineLabel: "Party · Riverside",
            price: "moderate",
            priceLabel: "€5–12 entry",
            area: "Zemun",
            address: "Kej oslobođenja bb, Zemun",
            rating: 4.5,
            description:
                "Riverside party venue in charming old Zemun with open-air terrace",
            lat: 44.839,
            lng: 20.4006,
            image: "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=600&q=80",
        },
        {
            name: "Tube",
            cuisine: "electronic",
            cuisineLabel: "Underground · House",
            price: "moderate",
            priceLabel: "€5–10 entry",
            area: "Stari Grad",
            address: "Simina 21, Stari Grad",
            rating: 4.5,
            description:
                "Underground club with intimate dance floor and top house DJs",
            lat: 44.8199,
            lng: 20.4594,
            image: "https://images.unsplash.com/photo-1574169208507-84376144848b?w=600&q=80",
        },
        {
            name: "Mladost & Ludost",
            cuisine: "mainstream",
            cuisineLabel: "Pop · Turbofolk",
            price: "upscale",
            priceLabel: "€10–20 entry",
            area: "Novi Beograd",
            address: "Bulevar Arsenija Čarnojevića 56, Novi Beograd",
            rating: 4.4,
            description:
                'Massive party venue — the name means "Youth & Madness"',
            lat: 44.8065,
            lng: 20.423,
            image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80",
        },
        {
            name: "Hot Mess",
            cuisine: "mainstream",
            cuisineLabel: "R&B · Hip Hop",
            price: "upscale",
            priceLabel: "€10–20 entry",
            area: "Stari Grad",
            address: "Strahinjića Bana 30, Stari Grad",
            rating: 4.5,
            badge: "trending",
            description:
                "Glamorous late-night club with R&B, hip-hop and celebrity DJs",
            lat: 44.8202,
            lng: 20.4589,
            image: "https://images.unsplash.com/photo-1545128485-c400e7702b17?w=600&q=80",
        },
    ],

    attractions: [
        {
            name: "Kalemegdan Fortress",
            cuisine: "historic",
            cuisineLabel: "Historic Fortress",
            area: "Stari Grad",
            address: "Kalemegdan Park, Stari Grad",
            rating: 4.9,
            badge: "topRated",
            description:
                "Ancient fortress at the confluence of the Sava and Danube rivers",
            lat: 44.8227,
            lng: 20.4513,
            image: "assets/atractions/kalis.jfif",
        },
        {
            name: "Skadarlija Bohemian Quarter",
            cuisine: "cultural",
            cuisineLabel: "Bohemian Street",
            area: "Skadarlija",
            address: "Skadarska ulica, Skadarlija",
            rating: 4.8,
            badge: "popular",
            description:
                "Cobblestone street lined with kafanas, art galleries and street musicians",
            lat: 44.8183,
            lng: 20.4638,
            image: "assets/atractions/skadarl.jpg",
        },
        {
            name: "Ada Ciganlija",
            cuisine: "nature",
            cuisineLabel: "Beach · Recreation",
            area: "Čukarica",
            address: "Ada Ciganlija, Čukarica",
            rating: 4.9,
            badge: "topRated",
            description:
                "Belgrade's Sea — river island paradise with beaches, sports and cafés",
            lat: 44.7955,
            lng: 20.421,
            image: "assets/images/ada-ciganlija.jpg",
        },
        {
            name: "Saint Sava Temple",
            cuisine: "religious",
            cuisineLabel: "Orthodox Church",
            area: "Vračar",
            address: "Krušedolska 2a, Vračar",
            rating: 4.9,
            badge: "topRated",
            description:
                "One of the largest Orthodox churches in the world with stunning gold mosaics",
            lat: 44.7993,
            lng: 20.4671,
            image: "assets/atractions/sveti.jpg",
        },
        {
            name: "Nikola Tesla Museum",
            cuisine: "museum",
            cuisineLabel: "Science Museum",
            area: "Vračar",
            address: "Krunska 51, Vračar",
            rating: 4.8,
            badge: "popular",
            description:
                "The world's only museum dedicated to inventor Nikola Tesla with interactive exhibits",
            lat: 44.8085,
            lng: 20.466,
            image: "assets/atractions/nidza.jpg",
        },
        {
            name: "Topčider Park",
            cuisine: "nature",
            cuisineLabel: "Royal Park",
            area: "Topčider",
            address: "Topčiderski park, Topčider",
            rating: 4.7,
            description:
                "Royal park with 200-year-old plane trees and elegant pavilions",
            lat: 44.7837,
            lng: 20.446,
            image: "assets/images/topcider-park.jpg",
        },
        {
            name: "Gardoš Tower",
            cuisine: "historic",
            cuisineLabel: "Historic Tower",
            area: "Zemun",
            address: "Gardoš, Zemun",
            rating: 4.7,
            badge: "popular",
            description:
                "Millennium Tower with panoramic views of the Danube and old Zemun",
            lat: 44.8427,
            lng: 20.3974,
            image: "assets/atractions/gardos.jpg",
        },
        {
            name: "National Museum",
            cuisine: "museum",
            cuisineLabel: "Art & History Museum",
            area: "Stari Grad",
            address: "Trg Republike 1a, Stari Grad",
            rating: 4.6,
            description:
                "Serbia's largest museum with 400,000+ artifacts spanning 3,000 years",
            lat: 44.8184,
            lng: 20.4577,
            image: "assets/atractions/muzej nac.jpg",
        },
        {
            name: "Zemun Quay",
            cuisine: "nature",
            cuisineLabel: "Riverside Walk",
            area: "Zemun",
            address: "Kej oslobođenja, Zemun",
            rating: 4.7,
            badge: "trending",
            description:
                "Charming riverside promenade with cafés, swans and Danube sunsets",
            lat: 44.8397,
            lng: 20.4011,
            image: "assets/atractions/zemun.jpeg",
        },
        {
            name: "Belgrade Fortress Military Museum",
            cuisine: "museum",
            cuisineLabel: "Military Museum",
            area: "Stari Grad",
            address: "Kalemegdan bb, Stari Grad",
            rating: 4.5,
            description:
                "Outdoor tanks and artillery plus indoor exhibits tracing Serbia's military history",
            lat: 44.823,
            lng: 20.4518,
            image: "assets/atractions/miltary.jfif",
        },
    ],
};
