'use strict';

window.FEELBG_VENUES = {
    restaurants: [
        {
            name: 'Ambar',
            cuisine: 'serbian',
            cuisineLabel: 'Serbian Cuisine',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Stari Grad',
            address: 'Karađorđeva 2-4, Stari Grad',
            rating: 4.9,
            badge: 'topRated',
            description: 'Award-winning Balkan cuisine with unlimited small plates and Sava river views',
            lat: 44.8135, lng: 20.4528,
            image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80'
        },
        {
            name: 'Tri Šešira',
            cuisine: 'serbian',
            cuisineLabel: 'Traditional Serbian',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Skadarlija',
            address: 'Skadarska 29, Skadarlija',
            rating: 4.7,
            badge: 'popular',
            description: 'Iconic Skadarlija kafana serving traditional Serbian dishes since 1864',
            lat: 44.8185, lng: 20.4632,
            image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80'
        },
        {
            name: 'Salon 1905',
            cuisine: 'serbian',
            cuisineLabel: 'Serbian Fine Dining',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Stari Grad',
            address: 'Kralja Petra 6, Stari Grad',
            rating: 4.9,
            badge: 'topRated',
            description: 'Elegant Serbian cuisine with live orchestra in a Belle Époque salon',
            lat: 44.8196, lng: 20.4601,
            image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80'
        },
        {
            name: 'Lorenzo & Kakalamba',
            cuisine: 'fineDining',
            cuisineLabel: 'Fine Dining · Fusion',
            price: 'fine-dining',
            priceLabel: '$$$$',
            area: 'Stari Grad',
            address: 'Cvijićeva 110, Stari Grad',
            rating: 4.9,
            badge: 'topRated',
            description: 'Theatrical fine dining with a multi-course tasting menu experience',
            lat: 44.8210, lng: 20.4561,
            image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80'
        },
        {
            name: 'Znak Pitanja',
            cuisine: 'serbian',
            cuisineLabel: 'Traditional Serbian',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Stari Grad',
            address: 'Kralja Petra 6, Stari Grad',
            rating: 4.8,
            badge: 'popular',
            description: 'Belgrade\'s oldest restaurant (1823) — The Question Mark kafana',
            lat: 44.8202, lng: 20.4589,
            image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80'
        },
        {
            name: 'Little Bay',
            cuisine: 'international',
            cuisineLabel: 'International · Bistro',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Stari Grad',
            address: 'Dositejeva 9a, Stari Grad',
            rating: 4.8,
            description: 'Opera-themed bistro with nightly classical performances',
            lat: 44.8199, lng: 20.4594,
            image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600&q=80'
        },
        {
            name: 'Manufaktura',
            cuisine: 'contemporary',
            cuisineLabel: 'Modern Serbian',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Dorćol',
            address: 'Kralja Petra 13, Dorćol',
            rating: 4.5,
            description: 'Modern Serbian craft gastronomy in a hip industrial setting',
            lat: 44.8226, lng: 20.4638,
            image: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&q=80'
        },
        {
            name: 'Mala Fabrika Ukusa',
            cuisine: 'serbian',
            cuisineLabel: 'Serbian · Artisan',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Vračar',
            address: 'Svetozara Markovića 48, Vračar',
            rating: 4.8,
            badge: 'popular',
            description: 'Small Factory of Taste — artisan Serbian plates with creative twists',
            lat: 44.8073, lng: 20.4701,
            image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80'
        },
        {
            name: 'Comunale Caffè e Cucina',
            cuisine: 'italian',
            cuisineLabel: 'Italian Cuisine',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Stari Grad',
            address: 'Knez Mihailova 12, Stari Grad',
            rating: 4.6,
            description: 'Authentic Italian in the heart of Belgrade\'s main pedestrian street',
            lat: 44.8184, lng: 20.4577,
            image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600&q=80'
        },
        {
            name: 'Bella Napoli',
            cuisine: 'italian',
            cuisineLabel: 'Italian · Pizza',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Stari Grad',
            address: 'Strahinjića Bana 49, Stari Grad',
            rating: 4.5,
            description: 'Wood-fired Neapolitan pizza and fresh pasta in a lively trattoria',
            lat: 44.8208, lng: 20.4572,
            image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80'
        },
        {
            name: 'Sakura',
            cuisine: 'japanese',
            cuisineLabel: 'Japanese · Sushi',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Stari Grad',
            address: 'Strahinjića Bana 63, Stari Grad',
            rating: 4.7,
            badge: 'trending',
            description: 'Premium Japanese sushi and sashimi with sake pairing menu',
            lat: 44.8214, lng: 20.4555,
            image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80'
        },
        {
            name: 'Dva Jelena',
            cuisine: 'serbian',
            cuisineLabel: 'Traditional Serbian',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Skadarlija',
            address: 'Skadarska 32, Skadarlija',
            rating: 4.7,
            badge: 'popular',
            description: 'Two Deer — legendary Skadarlija kafana with tamburitza music',
            lat: 44.8180, lng: 20.4640,
            image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80'
        },
        {
            name: 'Franš',
            cuisine: 'mediterranean',
            cuisineLabel: 'French · Mediterranean',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Dorćol',
            address: 'Đure Jakšića 3, Dorćol',
            rating: 4.7,
            description: 'Refined French-Mediterranean cuisine in a charming courtyard',
            lat: 44.8231, lng: 20.4647,
            image: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=600&q=80'
        },
        {
            name: 'Langouste',
            cuisine: 'seafood',
            cuisineLabel: 'Seafood · Mediterranean',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Dorćol',
            address: 'Strahinjića Bana 76, Dorćol',
            rating: 4.6,
            description: 'Fresh Adriatic seafood and Mediterranean specialties',
            lat: 44.8220, lng: 20.4648,
            image: 'https://images.unsplash.com/photo-1515669097368-22e68427d265?w=600&q=80'
        },
        {
            name: 'Bela Reka',
            cuisine: 'serbian',
            cuisineLabel: 'Serbian · Grill',
            price: 'budget',
            priceLabel: '$ - $$',
            area: 'Stari Grad',
            address: 'Skadarska 15, Stari Grad',
            rating: 4.4,
            description: 'Hearty Serbian grill and traditional comfort food at local prices',
            lat: 44.8197, lng: 20.4592,
            image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&q=80'
        },
    ],

    cafes: [
        {
            name: 'Supermarket Bar',
            cuisine: 'cocktail',
            cuisineLabel: 'Cocktail · Rooftop',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Savamala',
            address: 'Karađorđeva 44, Savamala',
            rating: 4.7,
            badge: 'popular',
            description: 'Trendy rooftop cocktail bar in the heart of Savamala district',
            lat: 44.8141, lng: 20.4521,
            image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=80'
        },
        {
            name: 'Smokvica',
            cuisine: 'mediterranean',
            cuisineLabel: 'Wine · Mediterranean',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Dorćol',
            address: 'Kralja Petra 73, Dorćol',
            rating: 4.8,
            badge: 'topRated',
            description: 'Chic Mediterranean wine bar with a lush garden patio',
            lat: 44.8226, lng: 20.4638,
            image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&q=80'
        },
        {
            name: 'Stara Čukara',
            cuisine: 'coffee',
            cuisineLabel: 'Traditional Coffee',
            price: 'budget',
            priceLabel: '$ - $$',
            area: 'Stari Grad',
            address: 'Cara Uroša 16, Stari Grad',
            rating: 4.6,
            description: 'Old Belgrade coffee house with live acoustic music and Turkish coffee',
            lat: 44.8208, lng: 20.4572,
            image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80'
        },
        {
            name: 'Cantina del Gusto',
            cuisine: 'wine',
            cuisineLabel: 'Wine Bar',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Vračar',
            address: 'Bulevar Kralja Aleksandra 52, Vračar',
            rating: 4.7,
            description: 'Premium Serbian wine selection with antipasti platters',
            lat: 44.8067, lng: 20.4690,
            image: 'https://images.unsplash.com/photo-1516594798947-e65505dbb29d?w=600&q=80'
        },
        {
            name: 'Mint Rooftop Bar',
            cuisine: 'cocktail',
            cuisineLabel: 'Cocktail · Lounge',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Novi Beograd',
            address: 'Bulevar Mihajla Pupina 10, Novi Beograd',
            rating: 4.9,
            badge: 'topRated',
            description: 'Sky-high cocktails with panoramic views of Belgrade from the 18th floor',
            lat: 44.8058, lng: 20.4198,
            image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&q=80'
        },
        {
            name: 'Caffe Imperiale',
            cuisine: 'coffee',
            cuisineLabel: 'European Café',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Stari Grad',
            address: 'Knez Mihailova 34, Stari Grad',
            rating: 4.5,
            description: 'Grand European-style café with artisan pastries and espresso',
            lat: 44.8214, lng: 20.4555,
            image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&q=80'
        },
        {
            name: 'Rekord Bar',
            cuisine: 'craft',
            cuisineLabel: 'Vinyl · Craft Beer',
            price: 'budget',
            priceLabel: '$ - $$',
            area: 'Dorćol',
            address: 'Gospodar Jevremova 28, Dorćol',
            rating: 4.6,
            badge: 'trending',
            description: 'Vinyl record bar with rotating craft beer selection and retro vibes',
            lat: 44.8231, lng: 20.4647,
            image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&q=80'
        },
        {
            name: 'Balkan Brew',
            cuisine: 'craft',
            cuisineLabel: 'Craft Brewery',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Savamala',
            address: 'Karađorđeva 61, Savamala',
            rating: 4.7,
            badge: 'popular',
            description: 'Craft brewery with 20+ local beers on tap and brewery tours',
            lat: 44.8130, lng: 20.4533,
            image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&q=80'
        },
        {
            name: 'Toro Latin GastroBar',
            cuisine: 'cocktail',
            cuisineLabel: 'Latin · Cocktail',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Stari Grad',
            address: 'Strahinjića Bana 55, Stari Grad',
            rating: 4.6,
            description: 'Latin-inspired cocktails with tapas in a vibrant setting',
            lat: 44.8204, lng: 20.4583,
            image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80'
        },
        {
            name: 'Kafeterija',
            cuisine: 'coffee',
            cuisineLabel: 'Specialty Coffee',
            price: 'budget',
            priceLabel: '$ - $$',
            area: 'Vračar',
            address: 'Internacionalnih brigada 55, Vračar',
            rating: 4.5,
            description: 'Third-wave specialty coffee roasters with pour-over bar',
            lat: 44.8081, lng: 20.4685,
            image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80'
        },
    ],

    nightlife: [
        {
            name: 'Klub 20/44',
            cuisine: 'electronic',
            cuisineLabel: 'Electronic · Techno',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Savamala',
            address: 'Savski kej bb, Savamala',
            rating: 4.8,
            badge: 'topRated',
            description: 'Premier club for electronic music on the Sava river bank',
            lat: 44.8138, lng: 20.4516,
            image: 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80'
        },
        {
            name: 'Freestyler Boat Club',
            cuisine: 'mainstream',
            cuisineLabel: 'Pop · Dance',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Sava',
            address: 'Brod Freestyler, Sava River',
            rating: 4.7,
            badge: 'popular',
            description: 'Legendary floating nightclub on the Sava river with top DJs',
            lat: 44.8148, lng: 20.4490,
            image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80'
        },
        {
            name: 'Drugstore Club',
            cuisine: 'electronic',
            cuisineLabel: 'Techno · Underground',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Savamala',
            address: 'Bulevar vojvode Mišića 12, Savamala',
            rating: 4.7,
            badge: 'trending',
            description: 'Open-air electronic music venue near Beton Hala',
            lat: 44.8145, lng: 20.4502,
            image: 'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=600&q=80'
        },
        {
            name: 'Ksenija Jazz Club',
            cuisine: 'jazz',
            cuisineLabel: 'Jazz · Live Music',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Stari Grad',
            address: 'Kralja Petra 56, Stari Grad',
            rating: 4.9,
            badge: 'topRated',
            description: 'Intimate jazz venue with world-class live performances',
            lat: 44.8204, lng: 20.4583,
            image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&q=80'
        },
        {
            name: 'Ben Akiba Stand-Up',
            cuisine: 'comedy',
            cuisineLabel: 'Comedy · Entertainment',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Stari Grad',
            address: 'Nušićeva 8, Stari Grad',
            rating: 4.6,
            description: 'Belgrade\'s premier comedy club with local and international acts',
            lat: 44.8197, lng: 20.4592,
            image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=600&q=80'
        },
        {
            name: 'Brankow',
            cuisine: 'alternative',
            cuisineLabel: 'Alternative · Art',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Savamala',
            address: 'Karađorđeva 43, Savamala',
            rating: 4.6,
            badge: 'popular',
            description: 'Art-meets-nightlife venue with rooftop overlooking the Sava',
            lat: 44.8135, lng: 20.4528,
            image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80'
        },
        {
            name: 'Lasta Club',
            cuisine: 'mainstream',
            cuisineLabel: 'Party · Riverside',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Zemun',
            address: 'Kej oslobođenja bb, Zemun',
            rating: 4.5,
            description: 'Riverside party venue in charming old Zemun with open-air terrace',
            lat: 44.8390, lng: 20.4006,
            image: 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=600&q=80'
        },
        {
            name: 'Tube',
            cuisine: 'electronic',
            cuisineLabel: 'Underground · House',
            price: 'moderate',
            priceLabel: '$$ - $$$',
            area: 'Stari Grad',
            address: 'Simina 21, Stari Grad',
            rating: 4.5,
            description: 'Underground club with intimate dance floor and top house DJs',
            lat: 44.8199, lng: 20.4594,
            image: 'https://images.unsplash.com/photo-1574169208507-84376144848b?w=600&q=80'
        },
        {
            name: 'Mladost & Ludost',
            cuisine: 'mainstream',
            cuisineLabel: 'Pop · Turbofolk',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Novi Beograd',
            address: 'Bulevar Arsenija Čarnojevića 56, Novi Beograd',
            rating: 4.4,
            description: 'Massive party venue — the name means "Youth & Madness"',
            lat: 44.8065, lng: 20.4230,
            image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80'
        },
        {
            name: 'Hot Mess',
            cuisine: 'mainstream',
            cuisineLabel: 'R&B · Hip Hop',
            price: 'upscale',
            priceLabel: '$$$ - $$$$',
            area: 'Stari Grad',
            address: 'Strahinjića Bana 30, Stari Grad',
            rating: 4.5,
            badge: 'trending',
            description: 'Glamorous late-night club with R&B, hip-hop and celebrity DJs',
            lat: 44.8202, lng: 20.4589,
            image: 'https://images.unsplash.com/photo-1545128485-c400e7702b17?w=600&q=80'
        },
    ],

    attractions: [
        {
            name: 'Kalemegdan Fortress',
            cuisine: 'historic',
            cuisineLabel: 'Historic Fortress',
            price: 'free',
            priceLabel: 'Free',
            area: 'Stari Grad',
            address: 'Kalemegdan Park, Stari Grad',
            rating: 4.9,
            badge: 'topRated',
            description: 'Ancient fortress at the confluence of the Sava and Danube rivers',
            lat: 44.8227, lng: 20.4513,
            image: 'assets/images/kalemegdan-fortress.jpg'
        },
        {
            name: 'Skadarlija Bohemian Quarter',
            cuisine: 'cultural',
            cuisineLabel: 'Bohemian Street',
            price: 'free',
            priceLabel: 'Free',
            area: 'Skadarlija',
            address: 'Skadarska ulica, Skadarlija',
            rating: 4.8,
            badge: 'popular',
            description: 'Cobblestone street lined with kafanas, art galleries and street musicians',
            lat: 44.8183, lng: 20.4638,
            image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80'
        },
        {
            name: 'Ada Ciganlija',
            cuisine: 'nature',
            cuisineLabel: 'Beach · Recreation',
            price: 'free',
            priceLabel: 'Free',
            area: 'Čukarica',
            address: 'Ada Ciganlija, Čukarica',
            rating: 4.9,
            badge: 'topRated',
            description: 'Belgrade\'s Sea — river island paradise with beaches, sports and cafés',
            lat: 44.7955, lng: 20.4210,
            image: 'assets/images/ada-ciganlija.jpg'
        },
        {
            name: 'Saint Sava Temple',
            cuisine: 'religious',
            cuisineLabel: 'Orthodox Church',
            price: 'free',
            priceLabel: 'Free',
            area: 'Vračar',
            address: 'Krušedolska 2a, Vračar',
            rating: 4.9,
            badge: 'topRated',
            description: 'One of the largest Orthodox churches in the world with stunning gold mosaics',
            lat: 44.7993, lng: 20.4671,
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Hram_Svetog_Save_2019.jpg/1280px-Hram_Svetog_Save_2019.jpg'
        },
        {
            name: 'Nikola Tesla Museum',
            cuisine: 'museum',
            cuisineLabel: 'Science Museum',
            price: 'budget',
            priceLabel: '€3',
            area: 'Vračar',
            address: 'Krunska 51, Vračar',
            rating: 4.8,
            badge: 'popular',
            description: 'The world\'s only museum dedicated to inventor Nikola Tesla with interactive exhibits',
            lat: 44.8085, lng: 20.4660,
            image: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=600&q=80'
        },
        {
            name: 'Topčider Park',
            cuisine: 'nature',
            cuisineLabel: 'Royal Park',
            price: 'free',
            priceLabel: 'Free',
            area: 'Topčider',
            address: 'Topčiderski park, Topčider',
            rating: 4.7,
            description: 'Royal park with 200-year-old plane trees and elegant pavilions',
            lat: 44.7837, lng: 20.4460,
            image: 'assets/images/topcider-park.jpg'
        },
        {
            name: 'Gardoš Tower',
            cuisine: 'historic',
            cuisineLabel: 'Historic Tower',
            price: 'free',
            priceLabel: 'Free',
            area: 'Zemun',
            address: 'Gardoš, Zemun',
            rating: 4.7,
            badge: 'popular',
            description: 'Millennium Tower with panoramic views of the Danube and old Zemun',
            lat: 44.8427, lng: 20.3974,
            image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80'
        },
        {
            name: 'National Museum',
            cuisine: 'museum',
            cuisineLabel: 'Art & History Museum',
            price: 'budget',
            priceLabel: '€3',
            area: 'Stari Grad',
            address: 'Trg Republike 1a, Stari Grad',
            rating: 4.6,
            description: 'Serbia\'s largest museum with 400,000+ artifacts spanning 3,000 years',
            lat: 44.8184, lng: 20.4577,
            image: 'https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?w=600&q=80'
        },
        {
            name: 'Zemun Quay',
            cuisine: 'nature',
            cuisineLabel: 'Riverside Walk',
            price: 'free',
            priceLabel: 'Free',
            area: 'Zemun',
            address: 'Kej oslobođenja, Zemun',
            rating: 4.7,
            badge: 'trending',
            description: 'Charming riverside promenade with cafés, swans and Danube sunsets',
            lat: 44.8397, lng: 20.4011,
            image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=600&q=80'
        },
        {
            name: 'Belgrade Fortress Military Museum',
            cuisine: 'museum',
            cuisineLabel: 'Military Museum',
            price: 'budget',
            priceLabel: '€2',
            area: 'Stari Grad',
            address: 'Kalemegdan bb, Stari Grad',
            rating: 4.5,
            description: 'Outdoor tanks and artillery plus indoor exhibits tracing Serbia\'s military history',
            lat: 44.8230, lng: 20.4518,
            image: 'https://images.unsplash.com/photo-1569587112025-0d460e81a126?w=600&q=80'
        },
    ]
};
